from __future__ import annotations

from typing import Protocol

from .models import (
    Check,
    ClaimsResult,
    Comparisons,
    Context,
    Evaluation,
    Evidence,
    EvidenceResult,
    Page,
    Project,
    TopicAnalysis,
)


class AiProvider(Protocol):
    def translate_topic(self, analysis: TopicAnalysis, language: str) -> TopicAnalysis: ...
    def analyze_topic(self, context: Context) -> TopicAnalysis: ...
    def evaluate_source(self, context: Context, pages: list[Page]) -> Evaluation: ...
    def extract_evidence(self, context: Context, pages: list[Page]) -> EvidenceResult: ...
    def extract_claims(self, text: str) -> ClaimsResult: ...
    def check_claim(self, context: Context, claim: str, evidence: list[Evidence]) -> Check: ...
    def compare(self, context: Context, evidence: list[Evidence]) -> Comparisons: ...


class Repository(Protocol):
    def create(self, project: Project) -> None: ...
    def get(self, owner: str, project_id: str) -> Project: ...
    def list(self, owner: str) -> list[Project]: ...
    def save(self, project: Project) -> None: ...
    def delete(self, owner: str, project_id: str) -> None: ...
    def acquire(self, owner: str, project_id: str, label: str) -> str: ...
    def release(self, project_id: str, token: str) -> None: ...
    def operation(self, project_id: str) -> dict | None: ...
    def register(self, email: str, password_hash: str, role: str = "USER") -> str: ...
    def user(self, email: str) -> dict | None: ...
    def set_role(self, email: str, role: str) -> None: ...
    def session(self, token_hash: str, user_id: str, expires: float) -> None: ...
    def authenticate(self, token_hash: str) -> dict | None: ...
    def logout(self, token_hash: str) -> None: ...
    def notes(self, query: str) -> list[dict]: ...
    def post_note(self, owner: str, topic: str, note: str) -> None: ...
    def create_billing_order(self, order: dict) -> None: ...
    def billing_order(self, order_code: int) -> dict | None: ...
    def update_billing_order(self, order_code: int, **fields) -> None: ...
    def billing_orders(self, user_id: str) -> list[dict]: ...
    def billing_overview(self) -> dict: ...
    def project_billing_state(self, user_id: str, project_id: str) -> dict: ...
    def mark_billing_paid(self, order_code: int, paid_at: str, reference: str) -> int: ...
    def mark_billing_cancelled(self, order_code: int, status: str) -> int: ...


class PdfExtractor(Protocol):
    def extract(self, content: bytes) -> list[Page]: ...


class FileStorage(Protocol):
    def put(self, source_id: str, content: bytes) -> None: ...
    def read(self, source_id: str) -> bytes: ...
    def delete(self, source_id: str) -> None: ...
