import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, ChevronRight, LoaderCircle, MessageSquareText } from "lucide-react";
import { api } from "../api";
import { Empty, Notice, message } from "../ui";

type Item = { id: string; kind: "AI" | "PRODUCT"; module: string | null; helpful: boolean | null; reason: string | null; product_type: string | null; comment: string; metadata: Record<string, string>; status: "NEW" | "REVIEWED" | "RESOLVED"; created_at: string; user_email: string };
type Data = { summary: { total: number; helpful_rate: number | null; by_module: { module: string; helpful_rate: number; total: number }[] }; items: Item[] };
const label = (value: string | null) => (value || "—").replaceAll("_", " ").toLowerCase();
export default function AdminFeedback() {
  const [data, setData] = useState<Data | null>(null), [filter, setFilter] = useState("all"), [selected, setSelected] = useState<Item | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const load = useCallback(() => api<Data>(`/admin/feedback?category=${filter}`).then((next) => { setData(next); setSelected((current) => next.items.find((item) => item.id === current?.id) || null); }).catch((e) => setError(message(e))), [filter]);
  useEffect(() => { void load(); }, [load]);
  async function updateStatus(status: Item["status"]) { if (!selected) return; setBusy(true); try { await api(`/admin/feedback/${selected.id}`, "PATCH", { status }); await load(); } catch (e) { setError(message(e)); } finally { setBusy(false); } }
  if (error && !data) return <main className="page"><Notice>{error}<button onClick={() => void load()}>Try again</button></Notice></main>;
  if (!data) return <main className="page"><div className="loading"><LoaderCircle className="spin" /> Loading feedback…</div></main>;
  return <main className="page admin-feedback"><header className="page-heading"><div><span className="eyebrow">ADMIN · FEEDBACK</span><h1>Feedback</h1><p>User experience signal — not an AI accuracy rate.</p></div></header>
    <section className="feedback-summary"><article><small>Helpful</small><strong>{data.summary.helpful_rate == null ? "—" : `${data.summary.helpful_rate}%`}</strong><span>AI result feedback</span></article>{data.summary.by_module.map((item) => <article key={item.module}><small>{label(item.module)}</small><strong>{item.helpful_rate}%</strong><span>{item.total} responses</span></article>)}</section>
    <div className="feedback-filters" role="group" aria-label="Filter feedback">{[["all", "All"], ["negative", "Negative"], ["bug", "Bug"], ["suggestion", "Suggestion"]].map(([value, text]) => <button key={value} className={filter === value ? "active" : ""} onClick={() => setFilter(value)}>{text}</button>)}</div>
    <section className="feedback-admin-grid"><div className="feedback-list">{data.items.length ? data.items.map((item) => <button key={item.id} className={selected?.id === item.id ? "active" : ""} onClick={() => setSelected(item)}><span><b>{item.kind === "AI" ? (item.helpful ? "Helpful" : "Negative") : label(item.product_type)}</b><small>{label(item.module || item.reason)} · {new Date(item.created_at).toLocaleDateString()}</small></span><em className={`feedback-status ${item.status.toLowerCase()}`}>{label(item.status)}</em><ChevronRight size={17} /></button>) : <Empty icon={<MessageSquareText size={24} />} title="No feedback yet"><p>This filter has no feedback.</p></Empty>}</div>
      <aside className="feedback-detail">{selected ? <><div><span className={`feedback-status ${selected.status.toLowerCase()}`}>{label(selected.status)}</span><h2>{selected.kind === "AI" ? label(selected.reason) : label(selected.product_type)}</h2><p>{selected.comment || "No additional note."}</p></div><dl><dt>Module</dt><dd>{label(selected.module)}</dd><dt>From</dt><dd>{selected.user_email}</dd>{Object.entries(selected.metadata).map(([key, value]) => <><dt key={`${key}-k`}>{label(key)}</dt><dd key={`${key}-v`}>{value}</dd></>)}</dl><div className="actions">{(["NEW", "REVIEWED", "RESOLVED"] as const).map((status) => <button key={status} className={selected.status === status ? "primary" : ""} disabled={busy || selected.status === status} onClick={() => void updateStatus(status)}>{busy ? <LoaderCircle className="spin" size={15} /> : status === "RESOLVED" ? <CheckCircle2 size={15} /> : null}{label(status)}</button>)}</div></> : <p className="muted">Select feedback to review its detail.</p>}</aside></section></main>;
}
